Parameters:
  IndiaVPC:
    Description: this is VPC
    Type: String
    Default: IndiaVPC
  VpcStackName:
    Description: vpc
    Default: IndiaVPC
    Type: String

Resources:
  # Public subnet1
  Pubsub1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.0.0.0/27
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public Subnet 1
      VpcId:
        Fn::ImportValue: VPCId
    # Public subnet 2
  Pubsub2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.0.0.32/27
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public Subnet 2
      VpcId:
        Fn::ImportValue: VPCId
      # PRivate subnet1
  Prisub1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.0.0.64/27
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Private Subnet 1
      VpcId:
        Fn::ImportValue: !Sub VPCId
    # Public subnet 2
  Prisub2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [2, !GetAZs ""]
      CidrBlock: 10.0.0.126/27
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Private Subnet 2
      VpcId:
        Fn::ImportValue: VPCId

Outputs:
  Publicsubnet1:
    Description: Public Subnet 1 ID
    Export:
      Name: !Sub ${AWS::StackName}-Publicsubnet1
    Value: PublicSubnet1
  Publicsubnet2:
    Description: Public Subnet 2 ID
    Export:
      Name: !Sub ${AWS::StackName}-Publicsubnet2
    Value: PublicSubnet 2
  Privatesubnet1:
    Description: Private Subnet 1 ID
    Export:
      Name: !Sub ${AWS::StackName}-Privatesubnet1
    Value: PrivateSubnet1
  Privatesubnet2:
    Description: Private Subnet 2 ID
    Export:
      Name: !Sub ${AWS::StackName}-Privatesubnet2
    Value: PrivateSubnet2
