# orchestration of VPC, InternetGateway
Parameters:
  VPCCidrBlock:
    Type: String
    Default: 10.0.0.0/25
  Indiavpc:
    Description: this is for reference
    Type: String
    Default: IndiaVPC

#creating VPC by the name of India
Resources:
  IndiaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: VPCId
          Value: India
  # Creating IGW by the name of Ocean
  OceanIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Ocean
  # Attaching India to Ocean
  VPCattachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref OceanIGW
      VpcId: !Ref IndiaVPC

Outputs:
  IndiaVPC:
    Description: A ref to created VPC
    Value: !Ref IndiaVPC
